run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - sqlclosecheck
  # errcheck temporarily disabled - see issue op-ymws
  # TODO: re-enable after fixing unchecked error returns

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/openmusicplayer/backend
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
  max-issues-per-linter: 0
  max-same-issues: 0
