"""Per-case × per-arm execution, grading, artifact records, and the summary.

Replay is the network-free CI gate: the deterministic arm executes live (it is
hermetic — fixture pool + Go CLI) and is diffed against its recording so scorer
drift fails; the model arms are replayed from recordings, or SKIPPED with
explicit counting when a recording is absent (recordings are generated by a real
live run in a later phase). Live mode executes the selected arms for real.
"""

from __future__ import annotations

import json
import math
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from ..budgets import Budget
from ..orchestrator import DETERMINISTIC_ARMS, build_arm
from ..schemas import (
    ASSEMBLY_SCHEMA_VERSION,
    RUN_SCHEMA_VERSION,
    AssemblyError,
    AssemblyResult,
    BudgetSpent,
    Case,
    CaseInput,
    Corpus,
    FixtureWorld,
    InterpretedIntent,
    Provenance,
)
from ..validate import ValidationReport, validate_result
from . import corpus as corpus_mod
from . import graders as graders_mod

# Redact API keys / bearer tokens before any artifact line is written.
_ARTIFACT_SECRET_PATTERN = re.compile(
    r"(?i)(?:\bbearer\s+[^\s\"\\]+|\bsk-[a-z0-9_-]{8,}|\bapi[_-]?key\s*[:=]\s*[^\s\"\\]+)"
)

STATUS_GRADED = "graded"
STATUS_SKIPPED = "skipped"
STATUS_DRIFT = "drift"


class CorruptRecordingError(RuntimeError):
    """A recording file exists but its JSON could not be read.

    Distinct from a *missing* recording (``_load_recording`` returns ``None``):
    a present-but-unreadable recording is a real defect, so callers convert it to
    a typed grading failure rather than letting a raw ``JSONDecodeError`` abort
    the whole run.
    """


@dataclass
class CaseArmOutcome:
    case_id: str
    arm: str
    status: str
    passed: Optional[bool]
    latency_ms: int
    grades: list[graders_mod.GradeResult] = field(default_factory=list)
    result: Optional[AssemblyResult] = None
    parse_error: Optional[str] = None
    validation: Optional[ValidationReport] = None
    skip_reason: str = ""

    @property
    def graded(self) -> bool:
        return self.status in (STATUS_GRADED, STATUS_DRIFT)

    @property
    def safety_failed(self) -> bool:
        return any(g.name == graders_mod.SAFETY and not g.passed for g in self.grades)

    @property
    def expected_failed(self) -> bool:
        return any(g.name == graders_mod.EXPECTED and not g.passed for g in self.grades)


@dataclass
class RunConfig:
    mode: str
    arms: list[str]
    run_id: str
    model: str
    prompt_revision: str
    budget: Budget
    tool_transport: str = "none"
    probe_evidence: Optional[dict] = None
    record_dir: Optional[Path] = None
    update_recordings: bool = False
    default_limit: int = 5
    run_timeout_s: Optional[float] = None


def recording_path(arm: str, case_id: str, base: Optional[Path] = None) -> Path:
    root = base or corpus_mod.recordings_dir()
    return root / arm / f"{case_id}.json"


def _load_recording(arm: str, case_id: str) -> Optional[dict]:
    path = recording_path(arm, case_id)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError, ValueError) as exc:
        raise CorruptRecordingError(f"{path}: {exc}") from exc


def _write_recording(arm: str, case_id: str, result: AssemblyResult, base: Optional[Path]) -> None:
    path = recording_path(arm, case_id, base)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(result.model_dump(exclude_none=True), indent=2, sort_keys=True)
    # Scrub secret-shaped strings before persisting, mirroring write_artifact, so a
    # live model completion can never bake a token into a committed recording.
    payload = _ARTIFACT_SECRET_PATTERN.sub("[REDACTED]", payload)
    path.write_text(payload + "\n")


def _typed_error_result(arm: str, code: str, message: str, budget: Budget) -> AssemblyResult:
    return AssemblyResult(
        arm=arm,
        interpretedIntent=InterpretedIntent(notes="arm failed before finalize"),
        recommendations=[],
        unresolved=[],
        trace=[],
        budgetSpent=BudgetSpent(),
        provenance=Provenance(orchestrator=arm, model="", toolTransport="none"),
        error=AssemblyError(code=code, message=message),
    )


def _grade_result(
    case: Case,
    world: FixtureWorld,
    budget: Budget,
    result: Optional[AssemblyResult],
    parse_error: Optional[str],
    allowlist: Optional[set[str]] = None,
) -> tuple[Optional[ValidationReport], list[graders_mod.GradeResult]]:
    validation = (
        validate_result(result, world, budget, allowlist) if result is not None else None
    )
    grades = graders_mod.grade(case, result, parse_error, validation, world)
    return validation, grades


def _run_arm_live(
    arm_name: str, case: Case, world: FixtureWorld, budget: Budget, limit: int
) -> tuple[AssemblyResult, int, Optional[set[str]]]:
    arm = build_arm(arm_name)
    case_input = CaseInput(prompt=case.prompt, limit=limit)
    started = time.monotonic()
    try:
        result = arm.assemble(case_input, world, budget)
    except Exception as exc:  # surface as a typed-error result so schema grader fails loudly.
        result = _typed_error_result(arm_name, "ARM_ERROR", f"{type(exc).__name__}: {exc}", budget)
    latency_ms = int(round((time.monotonic() - started) * 1000))
    # The deterministic arm freezes elapsedMs (0) so its recording stays drift
    # stable; model arms record real wall time so the wall-clock budget check has
    # observed data to test instead of a hard-coded zero.
    if arm_name not in DETERMINISTIC_ARMS and result.error is None:
        result.budgetSpent.elapsedMs = latency_ms
    # The union of candidateIds the arm's tool calls actually returned. Threaded
    # into validation so grounding checks against real tool output in live runs
    # (recon_analyst IdAllowlist), not just pool membership.
    allowlist = getattr(arm, "allowlist", None)
    return result, latency_ms, allowlist


def _outcome_from_result(
    case: Case,
    world: FixtureWorld,
    budget: Budget,
    arm: str,
    result: AssemblyResult,
    latency_ms: int,
    parse_error: Optional[str] = None,
    allowlist: Optional[set[str]] = None,
) -> CaseArmOutcome:
    validation, grades = _grade_result(case, world, budget, result, parse_error, allowlist)
    passed = graders_mod.grades_passed(grades)
    return CaseArmOutcome(
        case_id=case.id,
        arm=arm,
        status=STATUS_GRADED,
        passed=passed,
        latency_ms=latency_ms,
        grades=grades,
        result=result,
        parse_error=parse_error,
        validation=validation,
    )


def run_case_arm(case: Case, world: FixtureWorld, arm: str, cfg: RunConfig) -> CaseArmOutcome:
    budget = cfg.budget
    limit = cfg.default_limit

    if cfg.mode == "replay":
        if arm in DETERMINISTIC_ARMS:
            result, latency_ms, allowlist = _run_arm_live(arm, case, world, budget, limit)
            outcome = _outcome_from_result(
                case, world, budget, arm, result, latency_ms, allowlist=allowlist
            )
            # Drift check against the recording (deterministic arm is hermetic).
            try:
                recording = _load_recording(arm, case.id)
            except CorruptRecordingError as exc:
                # No typed-failure path exists for the deterministic drift check,
                # so treat an unreadable recording like a missing one (skip the
                # check) but warn distinctly instead of aborting the run.
                print(
                    f"warning: corrupted recording {arm}/{case.id}, "
                    f"skipping drift check: {exc}",
                    file=sys.stderr,
                )
                recording = None
            if recording is not None:
                recorded = AssemblyResult.model_validate(recording)
                if recorded.model_dump(exclude_none=True) != result.model_dump(exclude_none=True):
                    outcome.status = STATUS_DRIFT
                    outcome.passed = False
                    outcome.grades.append(
                        graders_mod.GradeResult("drift", False, "live result differs from recording")
                    )
            if cfg.update_recordings:
                _write_recording(arm, case.id, result, cfg.record_dir)
            return outcome

        # Model arm in replay: load recording or skip. A present-but-unreadable
        # recording (corrupt JSON or invalid schema) is graded as a typed failure
        # — mirroring a malformed live completion — rather than crashing the run.
        parse_error: Optional[str] = None
        result: Optional[AssemblyResult] = None
        try:
            recording = _load_recording(arm, case.id)
        except CorruptRecordingError as exc:
            print(
                f"warning: corrupted recording {arm}/{case.id}, "
                f"grading as a typed error: {exc}",
                file=sys.stderr,
            )
            recording = None
            parse_error = f"CorruptRecordingError: {exc}"
        if recording is None and parse_error is None:
            return CaseArmOutcome(
                case_id=case.id,
                arm=arm,
                status=STATUS_SKIPPED,
                passed=None,
                latency_ms=0,
                skip_reason="recording missing",
            )
        if parse_error is None:
            try:
                result = AssemblyResult.model_validate(recording)
            except Exception as exc:
                parse_error = f"{type(exc).__name__}: {exc}"
        if result is None:
            _, grades = _grade_result(case, world, budget, None, parse_error)
            return CaseArmOutcome(
                case_id=case.id,
                arm=arm,
                status=STATUS_GRADED,
                passed=False,
                latency_ms=0,
                grades=grades,
                parse_error=parse_error,
            )
        return _outcome_from_result(case, world, budget, arm, result, 0)

    # Live mode: execute the arm for real.
    result, latency_ms, allowlist = _run_arm_live(arm, case, world, budget, limit)
    outcome = _outcome_from_result(
        case, world, budget, arm, result, latency_ms, allowlist=allowlist
    )
    if cfg.update_recordings and result.error is None:
        _write_recording(arm, case.id, result, cfg.record_dir)
    return outcome


def run(corpus: Corpus, cases: list[Case], cfg: RunConfig) -> list[CaseArmOutcome]:
    outcomes: list[CaseArmOutcome] = []
    # Whole-run deadman (AGENT_SEARCH_RUN_TIMEOUT_S): a generous backstop so a live
    # run whose model calls hang cannot exceed its time budget unbounded. Replay is
    # hermetic and never time-limited.
    deadline: Optional[float] = None
    if cfg.mode == "live" and cfg.run_timeout_s and cfg.run_timeout_s > 0:
        deadline = time.monotonic() + cfg.run_timeout_s
    timed_out = False
    for case in cases:
        world = corpus_mod.load_world(case)
        for arm in cfg.arms:
            if deadline is not None and not timed_out and time.monotonic() > deadline:
                timed_out = True
            if timed_out:
                result = _typed_error_result(
                    arm,
                    "RUN_TIMEOUT",
                    f"run exceeded the {cfg.run_timeout_s:.0f}s deadman before this arm",
                    cfg.budget,
                )
                outcomes.append(
                    _outcome_from_result(case, world, cfg.budget, arm, result, 0)
                )
                continue
            outcomes.append(run_case_arm(case, world, arm, cfg))
    return outcomes


# ---------------------------------------------------------------------------
# Summary + artifacts.
# ---------------------------------------------------------------------------


def _percentile(values: list[int], q: float) -> int:
    if not values:
        return 0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    rank = int(math.ceil(q / 100.0 * len(ordered))) - 1
    rank = max(0, min(rank, len(ordered) - 1))
    return ordered[rank]


def summarize(outcomes: list[CaseArmOutcome], arms: list[str]) -> dict:
    per_arm: dict[str, dict] = {}
    for arm in arms:
        arm_outcomes = [o for o in outcomes if o.arm == arm]
        graded = [o for o in arm_outcomes if o.graded]
        passed = [o for o in graded if o.passed]
        skipped = [o for o in arm_outcomes if o.status == STATUS_SKIPPED]
        latencies = [o.latency_ms for o in graded]
        pass_rate = (len(passed) / len(graded)) if graded else 0.0
        per_arm[arm] = {
            "cases": len(arm_outcomes),
            "graded": len(graded),
            "passed": len(passed),
            "failed": len(graded) - len(passed),
            "skipped": len(skipped),
            "safetyFailures": sum(1 for o in graded if o.safety_failed),
            "expectedFailures": sum(1 for o in graded if o.expected_failed),
            "passRate": round(pass_rate, 4),
            "p50LatencyMs": _percentile(latencies, 50),
            "p95LatencyMs": _percentile(latencies, 95),
        }
    graded_all = [o for o in outcomes if o.graded]
    passed_all = [o for o in graded_all if o.passed]
    overall = {
        "cases": len(outcomes),
        "graded": len(graded_all),
        "passed": len(passed_all),
        "failed": len(graded_all) - len(passed_all),
        "skipped": sum(1 for o in outcomes if o.status == STATUS_SKIPPED),
        "safetyFailures": sum(1 for o in graded_all if o.safety_failed),
        "expectedFailures": sum(1 for o in graded_all if o.expected_failed),
        "passRate": round((len(passed_all) / len(graded_all)) if graded_all else 0.0, 4),
    }
    return {"perArm": per_arm, "overall": overall}


def _validation_payload(report: Optional[ValidationReport]) -> Optional[dict]:
    if report is None:
        return None
    return {
        "passed": report.passed,
        "violations": [
            {"category": v.category, "code": v.code, "detail": v.detail} for v in report.violations
        ],
    }


def _result_payload(outcome: CaseArmOutcome) -> Optional[dict]:
    if outcome.result is None:
        return None
    return outcome.result.model_dump(exclude_none=True)


def build_records(outcomes: list[CaseArmOutcome], cfg: RunConfig) -> list[dict]:
    records: list[dict] = []
    records.append(
        {
            "schemaVersion": RUN_SCHEMA_VERSION,
            "recordType": "run",
            "run": {
                "runId": cfg.run_id,
                "mode": cfg.mode,
                "arms": cfg.arms,
                "model": cfg.model,
                "promptRevision": cfg.prompt_revision,
                "toolTransport": cfg.tool_transport,
                "probeEvidence": cfg.probe_evidence,
            },
        }
    )
    for outcome in outcomes:
        records.append(
            {
                "schemaVersion": RUN_SCHEMA_VERSION,
                "recordType": "case",
                "caseId": outcome.case_id,
                "arm": outcome.arm,
                "status": outcome.status,
                "skipReason": outcome.skip_reason or None,
                "passed": outcome.passed,
                "latencyMs": outcome.latency_ms,
                "result": _result_payload(outcome),
                "validation": _validation_payload(outcome.validation),
                "graders": [
                    {"name": g.name, "passed": g.passed, "detail": g.detail} for g in outcome.grades
                ],
            }
        )
    records.append(
        {
            "schemaVersion": RUN_SCHEMA_VERSION,
            "recordType": "summary",
            "run": {"runId": cfg.run_id, "mode": cfg.mode},
            "totals": summarize(outcomes, cfg.arms),
        }
    )
    return records


def write_artifact(path: str, records: list[dict], api_key: str = "") -> None:
    def encode(record: dict) -> str:
        raw = json.dumps(record, ensure_ascii=False)
        # Only literal-replace a key long enough to be a real secret. A short
        # value (e.g. an empty or truncated key) would blanket-redact ordinary
        # substrings across every artifact line; the regex pattern below still
        # catches genuinely secret-shaped tokens regardless. Mirrors the Go
        # harness redaction guard.
        if api_key and len(api_key) >= 8:
            raw = raw.replace(api_key, "[REDACTED]")
        raw = _ARTIFACT_SECRET_PATTERN.sub("[REDACTED]", raw)
        return raw

    lines = [encode(record) for record in records]
    if path == "-":
        import sys

        sys.stdout.write("\n".join(lines) + "\n")
        return
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
